---
title: "Grid Sizes"
author: "Mazama Science"
date: "8/2/2019"
output: html_document
vignette: >
  %\VignetteIndexEntry{Grid Sizes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MazamaSatelliteUtils)
library(MazamaSpatialUtils)

setSatelliteDataDir("~/Data/Satellite")
setSpatialDataDir("~/Data/Spatial")

# get bbox for Texas
loadSpatialData("USCensusStates")
tx <- subset(USCensusStates, stateCode == "TX")
bb_tx <- sp::bbox(tx)

nc <- goesaodc_openFile("OR_ABI-L2-AODC-M6_G16_s20191291201274_e20191291204047_c20191291210009.nc")
pal <- colorRampPalette(c("khaki", "orangered"))

#par(mfrow=c(1, 3))
rstr <- goesaodc_createRaster(nc, bbox = bb_tx, res = 0.1)
raster::plot(rstr, "AOD", col = pal(100))
plot(tx, add = TRUE)

if(FALSE){
rstr <- goesaodc_createRaster(nc, bbox = bb_tx, res = 0.3)
raster::plot(rstr, "AOD", col = pal(100))
plot(tx, add = TRUE)

rstr <- goesaodc_createRaster(nc, bbox = bb_tx, res = 1.0)
raster::plot(rstr, "AOD", col = pal(100))
plot(tx, add = TRUE)
}
```

```{r, fig.width=10, fig.height=7, fig.align='center', echo=FALSE}
tb <- goesaodc_createTibble(nc)

# Subset for the east coast of Texas where there is a lot of dense data
bb_tx_dense <- c(-97, -96, 27, 28)
tb_tx_dense <- dplyr::filter(tb, 
                             lon > bb_tx_dense[1], lon < bb_tx_dense[2], 
                             lat > bb_tx_dense[3], lat < bb_tx_dense[4])
rstr <- goesaodc_createRaster(nc, 
                              lonLo = bb_tx_dense[1], lonHi = bb_tx_dense[2], 
                              latLo = bb_tx_dense[3], latHi = bb_tx_dense[4], 
                              res = 0.1, fun = mean)

# Define the AOD color palette
pal_aod <- colorRampPalette(c("khaki", "orangered"))

# Plot the raster colored with the AOD palette and draw all sample point locations
raster::plot(rstr, "AOD", col = pal_aod(25), xlim = bb_tx_dense[1:2], ylim = bb_tx_dense[3:4])
plot(tx, add = TRUE)
points(tb_tx_dense$lon, tb_tx_dense$lat, pch = 16, cex = 0.6, col = "black")
```

Drawing the sample points now with the same palette shows how the raster 
generalizes AOD readings for each tile:

```{r, fig.width=10, fig.height=7, fig.align='center', echo=FALSE}
# Assign each reading its own color based on the AOD palette
tb_tx_dense$col <- pal_aod(25)[as.numeric(cut(tb_tx_dense$AOD, breaks = 25))]

# Plot the raster and points, both now with the same AOD palette
raster::plot(rstr, "AOD", col = pal_aod(25), xlim = bb_tx_dense[1:2], ylim = bb_tx_dense[3:4])
plot(tx, add = TRUE)
points(tb_tx_dense$lon, tb_tx_dense$lat, pch = 16, cex = 0.6, col = tb_tx_dense$col)
```