---
title: "Chetco"
author: "Helen Miller"
date: "7/5/2018"
output: html_document
params:
  spatialDataDir: "~/Data/Spatial"
  maiacDataDir: "~/Data/maiac"
---
In this notebook we explore the Chetco fires data and compare it with results from the Napa fires.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Load packages
library(AirfireNasaMaiac)
library(PWFSLSmoke)
library(PWFSLSmokeModeling)
logger.setup()

# Get Params
spatialDataDir <- params$spatialDataDir
maiacDataDir <- params$maiacDataDir
setMaiacDataDir(maiacDataDir)

# load data
setSpatialDataDir(spatialDataDir)
loadSpatialData("USCensusStates")

napaFiles <- list.files("../localData", pattern = "napa_*", full.names = TRUE)
for (file in napaFiles) {
  load(file)
}

chetcoFiles <- list.files("../localData", pattern = "chetco_*", full.names = TRUE)
for (file in chetcoFiles) {
  load(file)
}

airnow <- airnow_load(2017)
wrcc <- wrcc_load(2017)
airsis <- airsis_load(2017)
all_monitors <- monitor_combine(list(airnow, wrcc, airsis))
monitors <- monitor_subset(all_monitors, xlim = c(-125, -118), ylim = c(39, 45))
fireMonitors <- monitor_subset(monitors, tlim = c(20170901, 20170909))
  
```


## Chetco Bar Context Map

```{r context_map, message = FALSE}
# Load full Chetco data from Sep 1 Aqua
sep01An <- maiac_loadRaster("h01v03", 20170901, 2050, converterPath = "../executables/h4toncff_nc4") 
sep01As <- maiac_loadRaster("h01v04", 20170901, 2045, converterPath = "../executables/h4toncff_nc4")
sep01A <- raster::merge(sep01An, sep01As)

# Define some colors to represent AOD 
colors <- colorRampPalette(c("white", "orange", "red"))(10)
# Breaks for coloring (relatively arbitrary at this point -- just based on what looks best visually)
breaks <- c(0, 0.03, 0.1, 0.2, 0.3, 0.5, 0.8, 1.5, 10)

# Reproject states polygons to projection of MAIAC data for context map
aeaStates <- spTransform(USCensusStates, CRS("+proj=aea +lat_1=20 +lat_2=60 +lon_0=-96 +lat_0=23 +datum=WGS84 +ellps=WGS84"))
# Point for Chetco Bar fire
chetco <- SpatialPoints(data.frame(x = -123.954, y = 42.297), proj4string = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  spTransform(CRS("+proj=aea +lat_1=20 +lat_2=60 +lon_0=-96 +lat_0=23 +datum=WGS84 +ellps=WGS84")) 
# Rectangle to show cropped area

crop <- SpatialPoints(data.frame(x = c(-125, -118, -118, -125, -125), y = c(39, 39, 45, 45, 39)), 
                        proj4string = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>%
  spTransform(CRS("+proj=aea +lat_1=20 +lat_2=60 +lon_0=-96 +lat_0=23 +datum=WGS84 +ellps=WGS84"))

# Draw the context map
plot(aeaStates, xlim = c(-3e+06, -1e+06), ylim = c(1e+06, 3.7e+06))
plot(sep01A, breaks = breaks, col = colors, colNA = "gray90", main = "Full data extent", add = TRUE, legend = FALSE)
plot(aeaStates, add = TRUE)
rect(xmin(sep01An), ymin(sep01An), xmax(sep01An), ymax(sep01An))
rect(xmin(sep01As), ymin(sep01As), xmax(sep01As), ymax(sep01As))
polygon(coordinates(crop)[,1], coordinates(crop)[,2] )
text(coordinates(crop)[1,1], coordinates(crop)[1,2], "cropped \nextent", pos = 1)
plot(chetco, add = TRUE)
text(xmin(chetco), ymin(chetco), "Chetco Bar Fire", pos = 3)
```

## Side-by-side plots of all days

```{r rasterplots}
rasterList <- list(chetco_AQUA_01, chetco_TERRA_01, chetco_AQUA_02, chetco_TERRA_02, chetco_AQUA_03, chetco_TERRA_03, 
                   chetco_AQUA_04, chetco_TERRA_04, chetco_AQUA_05, chetco_TERRA_05, chetco_AQUA_06, chetco_TERRA_06, 
                   chetco_AQUA_07, chetco_TERRA_07, chetco_AQUA_08, chetco_TERRA_08)
par(mfcol = c(1,2))
for ( i in 1:8 ) {
  AQUA <- rasterList[[i*2 - 1]]$corrected
  TERRA <- rasterList[[i*2]]$corrected
  day <- stringr::str_pad(i, 2, "left", "0")
  plot(TERRA, breaks = breaks, col = colors, colNA = "gray90", alpha = .8, main = "TERRA", legend = FALSE)
  plot(USCensusStates, add = TRUE)
  # Add monitors on top, colored based on the AQI category of the 3-hour centered rolling mean at the time of the satellite data collection
  monitor_subset(fireMonitors, tlim = paste0("201709", day, c("19", "20")) ) %>% 
    monitorMap(add = TRUE)
  mtext(paste0("Sept ", day), 2, 3, font = 2)
  plot(AQUA, breaks = breaks, col = colors, colNA = "gray90", alpha = .8, main = "AQUA", legend = FALSE)
  # Add monitors on top, colored based on the AQI category of the 3-hour centered rolling mean at the time of the satellite data collection
  monitor_subset(fireMonitors, tlim = paste0("201709", day, c("21", "22")) ) %>% 
    monitorMap(add = TRUE)
  plot(USCensusStates, add = TRUE)
}
```

## Values

```{r scatterplots}
hist(chetcodf$monitor, 100, main = "Chetco PM2.5")
hist(chetcodf$satellite, 100, main = "Chetco AOD")



plot(chetcodf$satellite, chetcodf$monitor, xlim = c(0, 3), ylim = c(0, 1500))
abline(lm(dfall$monitor~dfall$satellite), lty = 2, col = "red")
abline(lm(chetcodf$monitor~chetcodf$satellite), col = "red")

plot(dfall$satellite, dfall$monitor, xlim = c(0, 3), ylim = c(0, 1500))
abline(lm(dfall$monitor~dfall$satellite), lty = 2, col = "red")
abline(lm(chetcodf$monitor~chetcodf$satellite), col = "red")
```

## Values by day

```{r valuesbyday}
for (date in c('01', '02', '03', '04', '05', '06', '07', '08')) {
  data <- subset(chetcodf, day == date)
  plot(data$satellite, data$monitor, xlim = c(0, 3), ylim = c(0, 1500), main = paste0("Sept ", date))
}
```

## Thresholds

```{r thresholds}
# For napa smoke
dfall$moderate <- ifelse(dfall$monitor > 12, TRUE, FALSE)
dfall$usg <- ifelse(dfall$monitor > 35.5, TRUE, FALSE)
dfall$unhealthy <- ifelse(dfall$monitor > 55.5, TRUE, FALSE)
dfall$veryunhealthy <- ifelse(dfall$monitor > 150.5, TRUE, FALSE)
dfall$hazardous <- ifelse(dfall$monitor > 250.5, TRUE, FALSE)

napa_moderateglm <- glm(moderate~satellite, data = dfall, family = binomial)
napa_moderateThreshold <- -(napa_moderateglm$coefficients[1]/napa_moderateglm$coefficients[2])

napa_usgglm <- glm(usg~satellite, data = dfall, family = binomial)
napa_usgThreshold <- -(napa_usgglm$coefficients[1]/napa_usgglm$coefficients[2])

napa_unhealthyglm <- glm(unhealthy~satellite, data = dfall, family = binomial)
napa_unhealthyThreshold <- -(napa_unhealthyglm$coefficients[1]/napa_unhealthyglm$coefficients[2])

napa_veryunhealthyglm <- glm(veryunhealthy ~ satellite, data = dfall, family = binomial)
napa_veryunhealthyThreshold <- -(napa_veryunhealthyglm$coefficients[1]/napa_veryunhealthyglm$coefficients[2])

napa_hazardousglm <- glm(hazardous ~ satellite , data = dfall, family = binomial)
napa_hazardousThreshold <- -(napa_hazardousglm$coefficients[1]/napa_hazardousglm$coefficients[2])

napa_thresholds <- c(napa_moderateThreshold, napa_usgThreshold, napa_unhealthyThreshold, napa_veryunhealthyThreshold, napa_hazardousThreshold)
napa_intercepts <- exp(c(napa_moderateglm$coefficients[1], napa_usgglm$coefficients[1], napa_unhealthyglm$coefficients[1], napa_veryunhealthyglm$coefficients[1], napa_hazardousglm$coefficients[1]))
napa_slopes <- exp(c(napa_moderateglm$coefficients[2], napa_usgglm$coefficients[2], napa_unhealthyglm$coefficients[2], napa_veryunhealthyglm$coefficients[2], napa_hazardousglm$coefficients[2]))
napa_mcfadden <- c(pscl::pR2(napa_moderateglm)[4], pscl::pR2(napa_usgglm)[4], pscl::pR2(napa_unhealthyglm)[4], pscl::pR2(napa_veryunhealthyglm)[4], pscl::pR2(napa_hazardousglm)[4])

# For chetco smoke

chetcodf$moderate <- ifelse(chetcodf$monitor > 12, TRUE, FALSE)
chetcodf$usg <- ifelse(chetcodf$monitor > 35.5, TRUE, FALSE)
chetcodf$unhealthy <- ifelse(chetcodf$monitor > 55.5, TRUE, FALSE)
chetcodf$veryunhealthy <- ifelse(chetcodf$monitor > 150.5, TRUE, FALSE)
chetcodf$hazardous <- ifelse(chetcodf$monitor > 250.5, TRUE, FALSE)

chetco_moderateglm <- glm(moderate~satellite, data = chetcodf, family = binomial)
chetco_moderateThreshold <- -(chetco_moderateglm$coefficients[1]/chetco_moderateglm$coefficients[2])

chetco_usgglm <- glm(usg~satellite, data = chetcodf, family = binomial)
chetco_usgThreshold <- -(chetco_usgglm$coefficients[1]/chetco_usgglm$coefficients[2])

chetco_unhealthyglm <- glm(unhealthy~satellite, data = chetcodf, family = binomial)
chetco_unhealthyThreshold <- -(chetco_unhealthyglm$coefficients[1]/chetco_unhealthyglm$coefficients[2])

chetco_veryunhealthyglm <- glm(veryunhealthy ~ satellite, data = chetcodf, family = binomial)
chetco_veryunhealthyThreshold <- -(chetco_veryunhealthyglm$coefficients[1]/chetco_veryunhealthyglm$coefficients[2])

chetco_hazardousglm <- glm(hazardous ~ satellite , data = chetcodf, family = binomial)
chetco_hazardousThreshold <- -(chetco_hazardousglm$coefficients[1]/chetco_hazardousglm$coefficients[2])

chetco_thresholds <- c(chetco_moderateThreshold, chetco_usgThreshold, chetco_unhealthyThreshold, chetco_veryunhealthyThreshold, chetco_hazardousThreshold)
chetco_intercepts <- exp(c(chetco_moderateglm$coefficients[1], chetco_usgglm$coefficients[1], chetco_unhealthyglm$coefficients[1], chetco_veryunhealthyglm$coefficients[1], chetco_hazardousglm$coefficients[1]))
chetco_slopes <- exp(c(chetco_moderateglm$coefficients[2], chetco_usgglm$coefficients[2], chetco_unhealthyglm$coefficients[2], chetco_veryunhealthyglm$coefficients[2], chetco_hazardousglm$coefficients[2]))
chetco_mcfadden <- c(pscl::pR2(chetco_moderateglm)[4], pscl::pR2(chetco_usgglm)[4], pscl::pR2(chetco_unhealthyglm)[4], pscl::pR2(chetco_veryunhealthyglm)[4], pscl::pR2(chetco_hazardousglm)[4])
```

## Threshold plot

```{r thresholdplots}
plot(chetcodf$monitor~chetcodf$satellite, ylim = c(0, 500), xlab = "AOD", ylab = "PM2.5", main = "Threshold estimates")
points(chetco_thresholds, AQI$breaks_24[2:6], pch = 16, col = AQI$colors[-1], cex = 1.5)
points(napa_thresholds, AQI$breaks_24[2:6], pch = 17, col = AQI$colors[-1], cex = 1.5)
abline(lm(chetcodf$monitor~chetcodf$satellite), lty = 2, cex = 2)
abline(lm(dfall$monitor~dfall$satellite), lty = 3, cex = 2)
legend("topleft", legend = c("chetco lm", "napa lm", 'chetco', 'napa'), lty = c(2,3, NA, NA), pch = c(NA, NA, 16, 17), pt.cex = c(1,1,1.5,1.5))
```

## Threshold maps

```{r thresholdmaps}
par(mfcol = c(1,2))
for ( i in 1:8 ) {
  AQUA <- rasterList[[i*2 - 1]]$corrected
  TERRA <- rasterList[[i*2]]$corrected
  day <- stringr::str_pad(i, 2, "left", "0")
  plot(TERRA, breaks = c(0,napa_thresholds, 3), col = adjustcolor(AQI$colors, alpha.f = .3), colNA = "gray90", main = "TERRA (napa thresholds)", legend = FALSE)
  plot(USCensusStates, add = TRUE)
  # Add monitors on top, colored based on the AQI category of the 3-hour centered rolling mean at the time of the satellite data collection
  monitor_subset(fireMonitors, tlim = paste0("201709", day, c("19", "20")) ) %>% 
    monitorMap(add = TRUE)
  mtext(paste0("Sept ", day), 2, 3, font = 2)
  plot(TERRA, breaks = c(0, chetco_thresholds, 3), col = adjustcolor(AQI$colors, alpha.f = .3), colNA = "gray90", main = "TERRA (chetco thresholds)", legend = FALSE)
  plot(USCensusStates, add = TRUE)
  # Add monitors on top, colored based on the AQI category of the 3-hour centered rolling mean at the time of the satellite data collection
  monitor_subset(fireMonitors, tlim = paste0("201709", day, c("19", "20")) ) %>% 
    monitorMap(add = TRUE)
  
  plot(AQUA, breaks = c(0,napa_thresholds, 3), col = adjustcolor(AQI$colors, alpha.f = .3), colNA = "gray90", main = "AQUA (napa thresholds)", legend = FALSE)
  # Add monitors on top, colored based on the AQI category of the 3-hour centered rolling mean at the time of the satellite data collection
  monitor_subset(fireMonitors, tlim = paste0("201709", day, c("21", "22")) ) %>% 
    monitorMap(add = TRUE)
  mtext(paste0("Sept ", day), 2, 3, font = 2)
  plot(USCensusStates, add = TRUE)
  plot(AQUA, breaks = c(0,chetco_thresholds, 3), col = adjustcolor(AQI$colors, alpha.f = .3), colNA = "gray90", main = "AQUA (chetco thresholds)", legend = FALSE)
  # Add monitors on top, colored based on the AQI category of the 3-hour centered rolling mean at the time of the satellite data collection
  monitor_subset(fireMonitors, tlim = paste0("201709", day, c("21", "22")) ) %>% 
    monitorMap(add = TRUE)
  plot(USCensusStates, add = TRUE)
}
```




