---
title: "Exploring Spatial Variation"
author: "Helen Miller"
date: "6/25/2018"
output: html_document
params:
  spatialDataDir: "~/Data/Spatial"
  maiacDataDir: "~/Data/maiac"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Get Params
spatialDataDir <- params$spatialDataDir
maiacDataDir <- params$maiacDataDir
setMaiacDataDir(params$maiacDataDir)

# Load packages
library(AirfireNasaMaiac)
library(PWFSLSmoke)
library(PWFSLSmokeModeling)
library(raster)
logger.setup()


# load spatial data
setSpatialDataDir(spatialDataDir)
loadSpatialData("USCensusStates")
```

```{r loadingData, message=FALSE, cache=TRUE}
oct08Afull <- maiac_loadRaster("h01v04", 20171008, 2105, converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) 
oct08A <- projectRaster(oct08Afull, crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>%
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78)) 
oct08T <- maiac_loadRaster("h01v04", 20171008, 1930, product = "MAIACTAOT", converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>% 
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78))
oct09A <- maiac_loadRaster("h01v04", 20171009, 2150, converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78)) 
oct09Tpre <- maiac_loadRaster("h01v04", 20171009, product = "MAIACTAOT", converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0"))
oct09T <- focal(oct09Tpre, w=matrix(1,3,3), fun=mean, na.rm = TRUE)
oct10A <- maiac_loadRaster("h01v04", 20171010, converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78))
oct10T <- maiac_loadRaster("h01v04", 20171010, 1915, product = "MAIACTAOT", converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78))
oct11A <- maiac_loadRaster("h01v04", 20171011, 2135, converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78))
oct11T <- maiac_loadRaster("h01v04", 20171011, 1820, product = "MAIACTAOT", converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78)) 
oct12A <- maiac_loadRaster("h01v04", 20171012, 2040, converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78)) 
oct12T <- maiac_loadRaster("h01v04", 20171012, product = "MAIACTAOT", converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78))
oct13A <- maiac_loadRaster("h01v04", 20171013, converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78))
oct13T <- maiac_loadRaster("h01v04", 20171013, 1945, product = "MAIACTAOT", converterPath = "../executables/h4toncff_nc4", maiacDataDir = maiacDataDir) %>%
  projectRaster(crs = CRS("+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0")) %>% 
  crop(raster::extent(-125.52, -117.03, 36.52, 41.78))
```

```{r loadingMonitoringData, cache = TRUE, include = FALSE}
airnow <- airnow_load(2017)
wrcc <- wrcc_load(2017)
airsis <- airsis_load(2017)
all_monitors <- monitor_combine(list(airnow, wrcc, airsis))
monitors <- monitor_subset(all_monitors, xlim = c(-125.52, -117.03), ylim = c(36.52, 41.78))
fireMonitors <- monitor_subset(monitors, tlim = c(20171008, 20171014))
```

```{r buildDataSet, cache = TRUE, include = FALSE}
# define blank datafram to insert data into
dfa <- data_frame(monitorID = vector("character"),
                         monitor = vector("numeric"),
                         satellite = vector("numeric"),
                  day = vector("numeric"),
                  instrument = vector("character"),
                  rasterIndex = vector("numeric"),
                  longitude = vector("numeric"),
                  latitude = vector("numeric"))
dft <- dfa
monitorCount <- nrow(fireMonitors$meta)

rasterList <- list(oct08A, oct08T, oct09A, oct09T, oct10A, oct10T, oct11A, oct11T, oct12A, oct12T, oct13A, oct13T)

# Get the data for each day
for (i in 1:6) {
  
  # Select the correct rasters
  AQUA <- rasterList[[i*2 - 1]]
  TERRA <- rasterList[[i*2]]
  
  # Get the day of month as a zero-padded string
  day <- stringr::str_pad(i+7, 2, "left", "0")
  
  # Make blank dataframes for this day
  aquadf <- data_frame(monitorID = fireMonitors$meta$monitorID, 
                 monitor = vector("numeric", monitorCount),
                 satellite = vector("numeric", monitorCount), 
                 day = vector("numeric", monitorCount),
                 instrument = vector("character", monitorCount),
                 rasterIndex = vector("numeric", monitorCount),
                 longitude = vector("numeric", monitorCount),
                 latitude = vector("numeric", monitorCount))
  terradf <- aquadf
  
  # Get the the index for the correct day and time
  timeIndexA <- which(fireMonitors$data$datetime == lubridate::ymd_h(paste0("201710", day, "21")) )
  timeIndexT <- which(fireMonitors$data$datetime == lubridate::ymd_h(paste0("201710", day, "19")) )
  
  # Add monitor and satellite data for each monitor
  for (i in 1:monitorCount) {
    monitorInfo <- fireMonitors$meta[i,]
    aquadf[i,'monitor'] <- fireMonitors$data[timeIndexA, monitorInfo$monitorID]
    aquadf[i, 'satellite'] <- getValue(AQUA, monitorInfo$longitude, monitorInfo$latitude)
    aquadf[i, 'datetime'] <- lubridate::ymd_h(paste0("201710", day, "21"))
    aquadf[i, 'rasterIndex'] <- raster::cellFromXY(AQUA, c(monitorInfo$longitude, monitorInfo$latitude))
    aquadf[i, 'latitude'] <- monitorInfo$latitude
    aquadf[i, 'longitude'] <- monitorInfo$longitude
    terradf[i,'monitor'] <- fireMonitors$data[timeIndexT, monitorInfo$monitorID]
    terradf[i, 'satellite'] <- getValue(TERRA, monitorInfo$longitude, monitorInfo$latitude)
    terradf[i, 'datetime'] <- lubridate::ymd_h(paste0("201710", day, "19")) 
    terradf[i, 'rasterIndex'] <- raster::cellFromXY(TERRA, c(monitorInfo$longitude, monitorInfo$latitude))
    terradf[i, 'latitude'] <- monitorInfo$latitude
    terradf[i, 'longitude'] <- monitorInfo$longitude
  }
  
  # Add that day's worth of data to full data frame
  dfa <- add_row(dfa, monitorID = aquadf$monitorID, satellite = aquadf$satellite, monitor = aquadf$monitor, day = day, instrument = "aqua", rasterIndex = aquadf$rasterIndex, longitude = aquadf$longitude, latitude = aquadf$latitude)
  dft <- add_row(dft, monitorID = terradf$monitorID, satellite = terradf$satellite, monitor = terradf$monitor, day = day, instrument = "terra", rasterIndex = terradf$rasterIndex, longitude = terradf$longitude, latitude = terradf$latitude)
}

# Get data frame with data from both satellites
dfall <- add_row(dft, monitorID = dfa$monitorID, satellite = dfa$satellite, monitor = dfa$monitor, day = dfa$day, instrument = dfa$instrument, rasterIndex = dfa$rasterIndex, longitude = dfa$longitude, latitude = dfa$latitude)
lm <- lm(monitor~satellite, data = dfall)
```


```{r rumple}
land <- mask(oct09A, subset(USCensusStates, stateCode %in% c("CA", "NV")))
rumpled <- focal(land, w=matrix(1,3,3), fun=sd, na.rm = TRUE)
rumpled5 <- focal(land, w=matrix(1, 5, 5), fun=sd, na.rm = TRUE)
```

Fill in missing values the "right" way -- if NA, use mean of surrounding 3x3 square. If still NA, use mean of surrounding 5x5 square. Record whether value is filled in or not.

```{r missing}
mean3 <- focal(land, w = matrix(1,3,3), fun = mean, na.rm = TRUE)
mean5 <- focal(land, w = matrix(1,5,5), fun = mean, na.rm = TRUE)
mean3mask <- setValues(land, ifelse(is.na(values(land)) & !is.na(values(mean3)), TRUE, FALSE))
mean5mask <- setValues(land, ifelse(is.na(values(land)) & is.na(values(mean3)) & !is.na(values(mean5)), TRUE, FALSE))
land3 <- cover(land, mean3)
land5 <- cover(land3, mean5)
aod <- land5
```

```{r plots}
colors <- colorRampPalette(c("white", "orange", "red"))(9)
breaks <- c(0, 0.03, 0.1, 0.2, 0.3, 0.5, 0.8, 10)
plot(aod)
plot(USCensusStates, add = TRUE)
plot(rumpled)
plot(USCensusStates, add = TRUE)
plot(rumpled5)
plot(USCensusStates, add = TRUE)
hist(values(rumpled), 1000, xlim = c(0,.2))
plot(values(rumpled) ~ values(land))
```

Still looking at the simplist model, for October 9 AQUA:
This is a map of the residuals at each monitor location. Green is negative and pink is positive, with white near zero. 

```{r residuals}
newdata <- data.frame(satellite = values(aod))
predictions <- predict(lm, newdata)
dfday <- dfall[dfall$day == "09",]
residuals <- data.frame(aod = values(aod)[dfday$rasterIndex], prediction = predictions[dfday$rasterIndex], residual = dfday$monitor-predictions[dfday$rasterIndex], latitude = dfday$latitude, longitude = dfday$longitude)
colors <- colorRampPalette(colors = c("#31a354", "white", "#c51b8a"))(17)
breaks <- c(-400, -200, -100, -50, -40, -30, -20, -10, -5, 5, 10, 20, 30, 40, 50, 100, 200, 400)
colorIndex <- .bincode(residuals$residual, breaks = breaks)
plot(aod, breaks = c(0, 0.03, 0.1, 0.2, 0.3, 0.5, 0.8, 10), col = colorRampPalette(c("white", "gray40"))(9), legend = FALSE)
plot(USCensusStates, add = TRUE)
points(residuals$longitude, residuals$latitude, col = ifelse(is.na(residuals$residual), "transparent", "gray10"), bg = ifelse(is.na(residuals$residual), "transparent", colors[colorIndex]), pch = 21)
```


