---
title: "Modeling"
author: "Helen Miller"
date: "6/26/2018"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# Load packages
library(AirfireNasaMaiac)
library(PWFSLSmoke)
library(PWFSLSmokeModeling)
library(lme4)
library(dplyr)
library(tidyr)
logger.setup()


# load spatial data
setSpatialDataDir("~/data/spatial")
loadSpatialData("USCensusStates")


napaFiles <- list.files("../localData", pattern = "napa_*", full.names = TRUE)
for (file in napaFiles) {
  load(file)
}

chetcoFiles <- list.files("../localData", pattern = "chetco_*", full.names = TRUE)
for (file in chetcoFiles) {
  load(file)
}
```

In this notebook, I explore some options for modeling ground PM2.5 based on AOD. 


To start off, explore the data a bit. 


```{r explore}
# Total number of observations
nrow(dfall)
nrow(chetcodf)

# The number of missing values filled in by the 3x3 mean
sum(dfall$aod_3)
sum(chetcodf$aod_3)

# The number of missing values filled in by the 5x5 mean
sum(dfall$aod_5)
sum(chetcodf$aod_5)

# The number of meaningful 'height' observations
sum(dfall$height > 0)

# Overall distribution of monitoring values
hist(dfall$monitor, 100, main = "napa PM2.5")
hist(chetcodf$monitor, 100, main = "chetco pm2.5")

# Overall distribution of AOD
hist(dfall$satellite, 100, main = "napa AOD")
hist(chetcodf$satellite, 100, main = "chetco AOD")

# pm2.5 vs AOD
plot(dfall$monitor ~ dfall$satellite, xlab = "AOD", ylab = "PM2.5", main = "napa")
plot(chetcodf$monitor ~ chetcodf$satellite, main = "chetco", xlab = "AOD", ylab = "PM2.5")

# Functions to pull out intercept, slope, and r2
getIntercept <- function(x,y){
  lm <- lm(y~x)
  return(lm$coefficients[1])
}
getSlope <- function(x,y){
  lm <- lm(y~x)
  return(lm$coefficients[2])
}
getR2 <- function(x,y){
  lm <- lm(y~x)
  return(summary(lm)$adj.r.squared)
}


# Mean AOD for each monitor
agg <- dfall %>% group_by(monitorID) %>% summarise(meanpm25 = mean(monitor, na.rm = TRUE), meanAOD = mean(satellite, na.rm = TRUE), sdpm25 = sd(monitor, na.rm = TRUE), sdAOD = sd(satellite, na.rm = TRUE))

ch_agg <- chetcodf %>% group_by(monitorID) %>% summarise(meanpm25 = mean(monitor, na.rm = TRUE), meanAOD = mean(satellite, na.rm = TRUE), sdpm25 = sd(monitor, na.rm = TRUE), sdAOD = sd(satellite, na.rm = TRUE))

hist(agg$meanAOD, 50, main = "Mean AOD value per monitor (napa)")
hist(ch_agg$meanAOD, 50, main = "Mean AOD value per monitor (chetco)")

# Mean pm2.5 for each monitor
hist(agg$meanpm25, 100, main = "Mean PM2.5 value per monitor")
hist(ch_agg$meanpm25, 100, main = "Mean PM2.5 values per monitor (chetco)")


# Some more summary plots
plot(agg$meanAOD ~ agg$meanpm25, xlab = "mean pm2.5", ylab = "mean AOD", main = "Mean AOD and PM2.5 per monitor (napa)")
plot(ch_agg$meanAOD ~ ch_agg$meanpm25, xlab = "mean pm2.5", ylab = "mean AOD", main = "Mean AOD and PM2.5 per monitor (chetco)")

plot(agg$sdAOD ~ agg$sdpm25, xlab = "pm2.5", ylab = "AOD", main = "Standard deviation of AOD and PM2.5 by monitor (napa)")
plot(ch_agg$sdAOD ~ ch_agg$sdpm25, xlab = "pm2.5", ylab = "AOD", main = "Standard deviation of AOD and PM2.5 by monitor (chetco)")

plot(agg$sdAOD ~ agg$meanAOD, main = "sd and mean of AOD per monitor (napa)", xlab = "standard deviation", ylab = "mean")
plot(ch_agg$sdAOD ~ ch_agg$meanAOD, main = "sd and mean of AOD per monitor (chetco)", xlab = "standard deviation", ylab = "mean")

plot(agg$sdpm25 ~ agg$meanpm25, main = "sd and mean = PM2.5", xlab = "standard deviation", ylab = "Mean")
plot(ch_agg$sdpm25 ~ ch_agg$meanpm25, main = "sd and mean = PM2.5", xlab = "standard deviation", ylab = "Mean")
```

```{r exploreMore}
# Explore linear models for each separate monitor
library(dplyr)
library(tidyr)
library(purrr)

by_mon <- dfall %>% group_by(monitorID) %>% nest()

aod_model <- function(df) {
  result <- try({
    lm1 <- lm(monitor~satellite, data = df)
    }, silent = TRUE)
  if ("try-error" %in% class(result)) {
    return(NA)
  } else {
    return(lm1) 
  }
}



models <- by_mon %>% 
  mutate(mod = purrr::map(data, aod_model)) %>%
  mutate(meanAOD = unlist(purrr::map(data, function(df) { mean(df$satellite, na.rm = TRUE) }))) %>%
  mutate(meanPM = unlist(purrr::map(data, function(df) { mean(df$monitor, na.rm = TRUE) } ))) %>%
  mutate(int = unlist(purrr::map(mod, function(mod) {if(!is.na(mod)[1]){mod$coefficients[1] } else {NA}  }))) %>%
  mutate(slope = unlist(purrr::map(mod, function(mod) { if(!is.na(mod)[1]){ mod$coefficients[2] } else {NA} }))) %>%
  mutate(r2 = unlist(purrr::map(mod, function(mod) {if (!is.na(mod)[1]){ summary(mod)$r.squared } else {NA} }))) %>%
  mutate(n = unlist(purrr::map(data, function(df) { sum(!is.na(df$monitor) & !is.na(df$satellite)) }))) %>% 
  mutate(longitude = unlist(purrr::map(data, function(df){ df$longitude[1] }))) %>%
  mutate(latitude = unlist(purrr::map(data, function(df){ df$latitude[1] }))) %>%
  filter(n >=6)

hist(models$int)
hist(models$slope)
hist(models$r2)
plot(models$slope, models$r2)
plot(models$meanPM, models$slope)
plot(models$meanPM, models$int)
plot(models$meanPM, models$r2)


# Map slope
breaks <- c(-Inf, -50, 0, 50, 100, 150, 200, Inf)
index <- .bincode(models$slope, breaks = breaks)
color <- colorRampPalette(c("yellow", "red"))(7)
plot(USCensusStates, xlim = c(-125.52, -117.03), ylim = c(36.52, 41.78))
points(models$longitude, models$latitude, col = color[index], pch = 16)

# Manually add a legend to the right side
usr <- par("usr")
legendbrks <- seq(usr[3], usr[4], length = length(breaks))
lx <- usr[2] + .6
rx <- usr[2] + .75
rect(lx,
     head(legendbrks, -1),
     rx,
     tail(legendbrks, -1),
     col = color,
     xpd = NA)
axis(4, at = legendbrks, labels = breaks, pos = rx, las = 2)
mtext("Slope", 4, line = 0.2)

# Map Int
breaks <- c(-Inf, -10, 0, 5, 10, 20, 30, Inf)
index <- .bincode(models$int, breaks = breaks)
color <- colorRampPalette(c("yellow", "red"))(7)
plot(USCensusStates, xlim = c(-125.52, -117.03), ylim = c(36.52, 41.78))
points(models$longitude, models$latitude, col = color[index], pch = 16)

# Manually add a legend to the right side
usr <- par("usr")
legendbrks <- seq(usr[3], usr[4], length = length(breaks))
lx <- usr[2] + .6
rx <- usr[2] + .75
rect(lx,
     head(legendbrks, -1),
     rx,
     tail(legendbrks, -1),
     col = color,
     xpd = NA)
axis(4, at = legendbrks, labels = breaks, pos = rx, las = 2)
mtext("Slope", 4, line = 0.2)

# Map r2
breaks <- c(0, .2, .4, .6, .8, 1)
index <- .bincode(models$r2, breaks = breaks)
color <- colorRampPalette(c("yellow", "red"))(5)
plot(USCensusStates, xlim = c(-125.52, -117.03), ylim = c(36.52, 41.78))
points(models$longitude, models$latitude, col = color[index], pch = 16)

# Manually add a legend to the right side
usr <- par("usr")
legendbrks <- seq(usr[3], usr[4], length = length(breaks))
lx <- usr[2] + .6
rx <- usr[2] + .75
rect(lx,
     head(legendbrks, -1),
     rx,
     tail(legendbrks, -1),
     col = color,
     xpd = NA)
axis(4, at = legendbrks, labels = breaks, pos = rx, las = 2)
mtext("R2", 4, line = 0.2)
```

Explore variation at different levels of the data

```{r variation}
# Napa
napa.mod <- lmer(monitor ~ 1 + (1|monitorID) + (1|day) + (1|instrument), data = dfall)
napa.summary <- summary(napa.mod)
napa.summary

# chetco
chetco.mod <- lmer(monitor ~ 1 + (1|monitorID) + (1|day) + (1|instrument), data = chetcodf)
summary(chetco.mod)
```

In the Napa data: 


```{r napaModel}
# fit some models

# 1. Do not account for correlation
model.0 <- lm(monitor ~ satellite, data = dfall)
summary(model.0)


# 2. Explore variation at the different levels
simple.a <- lmer(monitor ~ 1 + (1|monitorID), data = dfall)
summary(simple.a)

simple.b <- lmer(monitor ~ 1 + (1|monitorID) + (1|day), data = dfall)
summary(simple.b)

simple.c <- lmer(monitor ~ 1 + (1|monitorID) + (1|day) + (1|instrument), data = dfall)
summary(simple.c)

# 3. Add predictor

model.a <- lmer(monitor ~ satellite + (satellite|monitorID) + (satellite|day) + (satellite|instrument), data = dfall)
summary(model.a)

# Remove error terms so that it can hopefully converge

model.b <- lmer(monitor ~ satellite + (satellite|monitorID) + (satellite|day), data = dfall)
summary(model.b)

model.c <- lmer(monitor ~ satellite + (satellite|monitorID), data = dfall)
summary(model.c)

model.d <- lmer(monitor ~ satellite + (satellite|day), data = dfall)
summary(model.d)

model.e <- lmer(monitor ~ satellite + (satellite|day) + (1|monitorID), data = dfall)
summary(model.e)

anova(model.d, model.e)


# 2. experiment with adding a 'rumple' index
rumple.0 <- lmer(monitor ~ satellite + (satellite|day), data = dfall)
summary(rumple.0)

rumple.a <- lmer(monitor ~ satellite + (sd3|monitorID) , data = dfall)
summary(rumple.a)

rumple.a2 <- lmer(monitor ~ satellite + (sd3|day), data = dfall)
summary(rumple.a2)

rumple.a3 <- lmer(monitor ~ satellite + (sd3|monitorID) + (1|day), data = dfall)
summary(rumple.a3)

rumple.a4 <- lmer(monitor ~ satellite + (sd3|monitorID) + (satellite|day), data = dfall)
summary(rumple.a4)


rumple.b <- lmer(monitor ~ satellite + sd3 + (satellite|day), data = dfall)
summary(rumple.b)


rumple.c <- lmer(monitor ~ satellite + sd3 + satellite:sd3 + (1|monitorID), data = dfall)
summary(rumple.c)

anova(rumple.b, rumple.c)

rumple.d <- lmer(monitor ~ satellite + satellite:sd3 + (1|monitorID), data = dfall)
summary(rumple.d)

anova(rumple.c, rumple.d)

# 
```


```{r chetco}
# 1. Do not account for correlation
model.0 <- lm(monitor ~ satellite, data = chetcodf)
summary(model.0)


# 2. Explore variation at the different levels
simple.a <- lmer(monitor ~ 1 + (1|monitorID), data = chetcodf)
summary(simple.a)

simple.b <- lmer(monitor ~ 1 + (1|monitorID) + (1|day), data = chetcodf)
summary(simple.b)

simple.c <- lmer(monitor ~ 1 + (1|monitorID) + (1|day) + (1|instrument), data = chetcodf)
summary(simple.c)

# 3. Add predictor

model.a <- lmer(monitor ~ satellite + (satellite|monitorID) + (satellite|day) + (satellite|instrument), data = chetcodf)
summary(model.a)

# Remove error terms so that it can hopefully converge

model.b <- lmer(monitor ~ satellite + (satellite|monitorID) + (satellite|day), data = chetcodf)
summary(model.b)

model.c <- lmer(monitor ~ satellite + (satellite|monitorID), data = chetcodf)
summary(model.c)

model.d <- lmer(monitor ~ satellite + (satellite|day), data = chetcodf)
summary(model.d)

model.e <- lmer(monitor ~ satellite + (satellite|day) + (1|monitorID), data = chetcodf)
summary(model.e)

anova(model.d, model.e)


# 2. experiment with adding a 'rumple' index
rumple.0 <- lmer(monitor ~ satellite + (satellite|day), data = chetcodf)
summary(rumple.0)

rumple.a <- lmer(monitor ~ satellite + (sd3|monitorID) , data = chetcodf)
summary(rumple.a)

rumple.a2 <- lmer(monitor ~ satellite + (sd3|day), data = chetcodf)
summary(rumple.a2)

rumple.a3 <- lmer(monitor ~ satellite + (sd3|monitorID) + (1|day), data = chetcodf)
summary(rumple.a3)

rumple.a4 <- lmer(monitor ~ satellite + (sd3|monitorID) + (satellite|day), data = chetcodf)
summary(rumple.a4)


rumple.b <- lmer(monitor ~ satellite + sd3 + (satellite|day), data = chetcodf)
summary(rumple.b)


rumple.c <- lmer(monitor ~ satellite + sd3 + satellite:sd3 + (1|monitorID), data = chetcodf)
summary(rumple.c)

anova(rumple.b, rumple.c)

rumple.d <- lmer(monitor ~ satellite + satellite:sd3 + (1|monitorID), data = chetcodf)
summary(rumple.d)

anova(rumple.c, rumple.d)


```




