# GOESAOD documentation: https://data.nodc.noaa.gov/cgi-bin/iso?id=gov.noaa.ncdc:C01511
# https://tools-1.airfire.org/Satellite/GOES-16/AODC/

# Time to figure out the proj4 string!!!


library(MazamaSpatialUtils)
library(ncdf4)
library(raster)
library(rgdal)

# load .nc file
file_path <- file.path('../local_data','OR_ABI-L2-AODC-M3_G16_s20190781512186_e20190781514559_c20190781516459.nc')
nc <- ncdf4::nc_open(file_path)

# print(nc) yields:
#
# short AOD[x,y]   (Chunking: [226,226])  (Compression: level 1)
#     ...
#     grid_mapping: goes_imager_projection
#     ...
# int goes_imager_projection[]   (Contiguous storage)  
#     long_name: GOES-R ABI fixed grid projection
#     grid_mapping_name: geostationary
#     perspective_point_height: 35786023
#     semi_major_axis: 6378137
#     semi_minor_axis: 6356752.31414
#     inverse_flattening: 298.2572221
#     latitude_of_projection_origin: 0
#     longitude_of_projection_origin: -75
#     sweep_angle_axis: x
#     ...

# Hints on how to construct the proj4 string are here:
#   https://proj4.org/operations/projections/geos.html

# This site provides translations between netcdf and proj4 parameter names:
#  https://trac.osgeo.org/gdal/wiki/NetCDF_ProjectionTestingStatus

# So, if we ignore defining the ellipsoid and use the default GRS80, perhaps:

proj4_goes <- "+proj=geos +h=35786023 +lon_0=-75 +sweep=x +ellps=GRS80"

# Let's try

# get geospatial lat lon extent info
lat_lon_extent <- ncatt_get(nc, "geospatial_lat_lon_extent")
ymn <- lat_lon_extent$geospatial_southbound_latitude
ymx <- lat_lon_extent$geospatial_northbound_latitude
xmn <- lat_lon_extent$geospatial_westbound_longitude
xmx <- lat_lon_extent$geospatial_eastbound_longitude

# create AOD raster
aod <- ncvar_get(nc, "AOD")
aod_native_raster <- raster(t(aod),
                            xmn = xmn, 
                            xmx = xmx, 
                            ymn = ymn, 
                            ymx = ymx,
                            crs = (proj4_goes))

# These blog post point in the right direction:
#   https://www.neonscience.org/dc-reproject-raster-data-r

# We need to reproject this raster onto "regular" lon-lat coordiantes
# Trying:
proj4_default <- "+proj=longlat +ellps=GRS80 +datum=NAD83 +no_defs +towgs84=0,0,0"
proj4_default <- "+proj=longlat +datum=WGS84"

aod_raster <- projectRaster(aod_native_raster, crs = crs(proj4_default))

# Hmmm doesn't seem to do what I expected

# Maybe we need to projectExtent() as described here:
#   https://www.rdocumentation.org/packages/raster/versions/2.8-19/topics/projectRaster

aod_extent <- projectExtent(aod_native_raster, crs = crs(proj4_default))
# Adjust the cell size 
res(aod_extent) <- 1 # ??? Not sure of units
aod_raster <- projectRaster(aod_native_raster, aod_extent)

# Nope.


# Ooooh! This looks informative:
#   https://mgimond.github.io/megug2017/#raster-manipulation-basics

# And this:
#   https://www.neonscience.org/raster-data-r










# Attempting to recreate plot generated by Panoply (./AOD_in_OR_ABI-L2-AODC-M3_G16_s20190781512186_e20190781514559_c20190781516459.png)
setSpatialDataDir("~/Data/Spatial")
loadSpatialData("USCensusStates")
plot(aod_raster)
plot(USCensusStates, add=TRUE)

# looks as though AOD data is a bit west of where it should be.
# Also, the western most edge of the data is curved in the panolpy image, but
# not here.

