---
title: "Comparing GOES and BlueSky"
author: "Mazama Science"
date: "5/14/2021"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Comparing GOES and BlueSky}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
library(MazamaSatelliteUtils)
library(MazamaSpatialUtils)

setSatelliteDataDir("~/Data/Satellite")
setSpatialDataDir("~/Data/Spatial")

loadSpatialData("NaturalEarthAdm1")
```

```{r}
goesaodc_downloadScanFiles(
  satID = "G16",
  datetime = "2021-05-17 07:00",
  endtime = "2021-05-17 14:00",
  timezone = "America/Los_Angeles"
)

scanFile <- goesaodc_listScanFiles(
  satID = "G16",
  datetime = "2021-05-17 13:50",
  timezone = "America/Los_Angeles"
)

scanRaster <- goesaodc_createScanRaster(
  filename = scanFile,
  bbox = c(-109.5, -107.5, 26.5, 28),
  cellSize = 0.03
)

goesaodc_plotScanRaster(
  raster = scanRaster,
  bbox = c(-109.5, -107.5, 26.5, 28),
  rasterAlpha = 0.7,
  includeMap = TRUE,
  zoom = 8,
  title = scanFile %>% goesaodc_convertFilenameToDatetime()
)
```


```
./goesaodc_animateScanRasters_exec.R \
--satID="G16" \
--starttime="2021-05-17 09:00" \
--endtime="2021-05-17 14:00" \
--timezone="America/Los_Angeles" \
--bbox="-109.5, -107.5, 26.5, 28" \
--cellSize=0.03 \
--rasterAlpha=0.7 \
--legendLimits="-0.5, 5.5" \
--includeMap=TRUE \
--zoom=8 \
--stateCodes="CA" \
--satelliteDataDir="~/Data/Satellite" \
--spatialDataDir="~/Data/Spatial" \
--frameRate=10 \
--outputDir="~/Desktop" \
--logDir="~/Desktop" \
--verbose=TRUE
```