#' @export
#' 
#' @title Create a RasterStack of all files from the specified hour
#' 
#' @param datetime datetime, specified to the hour, in any Y-m-d H format or
#' \code{POSIXct}
#' @param var variable ("AOD, "DQF" or "ID")
#' @param res resolution of raster in degrees
#' @param fun function to use when rasterizing. Not currently supported, defaults
#' to mean.
#' @param bbox bounding box generated by \code{sp::bbox}. Overrides lonLo, lonHi
#' latLo, latHi if provided
#' @param lonLo lower longitude extent
#' @param lonHi upper longitude extent
#' @param latLo lower latitude extent
#' @param latHi upper latitude extent
#' @param dqfLevel data quality flag level, numeric (0, 1, 2, or 3)
#' 
#' @description Create a RasterStack of GOES AOD data of all files for a
#' specified hour. 
#' 
#' Data quality level can take a value of:
#' 
#' 0: High quality retrieval flag
#' 1: Medium quality retrieval flag
#' 2: Low quality retrieval flag
#' 3: No retrieval quality flag
#' 
#' @return RasterStack

goesaodc_createHourlyRasterStack <- function(
  datetime = NULL,
  var = "AOD",
  res = 0.1,
  fun = mean,
  bbox = NULL,
  lonLo = NULL,
  lonHi = NULL,
  latLo = NULL,
  latHi = NULL,
  dqfLevel = NULL
) {
  
  # ----- Validate Input -------------------------------------------------------
  
  if (!is.null(datetime)) {
    suppressWarnings({
      dt <- lubridate::parse_date_time(datetime, "YmdH", tz = "UTC")
    })
    if (is.na(dt)) {
      stop("Parameter 'datetime' must be specified to the hour")
    }
  } else {
    stop("Parameter 'datetime' is required")
  }
  
  # ----- Download GOES AOD Files ----------------------------------------------
  
  # make sure that files are downloaded
  date <- format(dt, "%Y%d%m")
  hour <- format(dt, "%H")
  
  goesaodc_downloadAOD(date = date, hour = hour)
  
  # ----- Create List of RasterLayers ------------------------------------------
  
  # create list of AOD raster layers for specified hour and region
  rasterList <- 
    goesaodc_listFiles(dt) %>%                          # create list of filenames for specified hour
    purrr::map(goesaodc_openFile) %>%                   # open each file in the list
    purrr::map(goesaodc_createRaster, res = res,        # rasterize each open file specified params
               # fun = fun,                             # NOTE: passing fun here does not work. Results in
               bbox = bbox,                             # NOTE: the following error: 
               lonLo = lonLo, lonHi = lonHi,            # NOTE: Error in fun(1) : could not find function "fun"
               latLo = latLo, latHi = latHi, 
               dqfLevel = dqfLevel) %>%  
    purrr::map(function(rst) rst[[var]])                # select RasterLayer of specified variable
  
  # ----- Create RasterStack ---------------------------------------------------
  
  # Extents won't match exactly and raster::stack() needs them to, so
  # find the largest extent necessary to encompass all RasterLayers in the
  # list, and apply that new extent to each of the RasterLayers.
  lonLo <- min(purrr::map_dbl(rasterList, function(rst) extent(rst)@xmin))
  lonHi <- max(purrr::map_dbl(rasterList, function(rst) extent(rst)@xmax))
  latLo <- min(purrr::map_dbl(rasterList, function(rst) extent(rst)@ymin))
  latHi <- max(purrr::map_dbl(rasterList, function(rst) extent(rst)@ymax))
  
  ext <- extent(c(lonLo, lonHi, latLo, latHi))
  
  rasterList <- purrr::map(rasterList, function(rst) setExtent(rst, ext))
  
  # now create the stack
  rasterStack <- raster::stack(rasterList)
  
  # assign times to the Z axis
  times <-
    goesaodc_listFiles(dt) %>%
    purrr::map_chr(goesaodc_getStartString) %>%
    purrr::map(lubridate::parse_date_time, orders = ("YjHMS"))
  
  rasterStack <- raster::setZ(rasterStack, times)
  # NOTE: Why does this prepend "X" to the names?
  names(rasterStack) <- purrr::map_chr(times, function(t) format(t, "%Hh%Mm"))
  
  return(rasterStack)
}

# ===== DEBUGGING ==============================================================

if (FALSE) {
  
  setSpatialDataDir("~/Data/Spatial")
  setSatelliteDataDir("~/Data/Satellite")
  
  # get bounding box for Pennsylvania
  loadSpatialData("USCensusStates")
  pa <- subset(USCensusStates, stateCode == "PA")
  bb_pa <- bbox(pa)
  
  # Set parameters
  datetime = "2019050912"
  var = "AOD"
  res = 0.1
  bbox = bb_pa
  
  # Create RasterStack
  rasterStack <- goesaodc_createHourlyRasterStack(
    datetime = datetime, var = var, res = res,  bbox = bbox)
  
  # Visualize!
  rasterVis::levelplot(rasterStack)
}

