#' @export
#' @importFrom rlang .data
#' 
#' @title Create a SpatialPointsDataFrame of GOES data
#' 
#' @param nc ncdf4 handle
#' @param bbox bounding box generated by \code{sp::bbox}. Overrides lonLo, lonHi
#' latLo, latHi if provided
#' @param lonLo lower longitude extent
#' @param lonHi upper longitude extent
#' @param latLo lower latitude extent
#' @param latHi upper latitude extent
#' @param dqfLevel data quality flag level
#' 
#' @description Create a SpatialPointsDataFrame of GOES data including data
#' within the specified extent and data quality flag level. Data quality level
#' can take a value of:
#' 
#' 0: High quality retrieval flag
#' 1: Medium quality retrieval flag
#' 2: Low quality retrieval flag
#' 3: No retrieval quality flag
#' 
#' @return SpatialPointsDataFrame
#' 
#' @examples 
#' \donttest{
#' setSatelliteDataDir("~/Data/Satellite")
#' nc <- goesaodc_openFile("OR_ABI-L2-AODC-M6_G16_s20191291201274_e20191291204047_c20191291210009.nc")
#' sp <- goesaodc_createSpatialPoints(nc, dqfLevel = 1)
#' }

goesaodc_createSpatialPoints <- function(
  nc,
  bbox = NULL,
  lonLo = NULL,
  lonHi = NULL,
  latLo = NULL,
  latHi = NULL,
  dqfLevel = NULL
) {
  
  # ----- Validate Parameters --------------------------------------------------
  
  if ( !is.null(dqfLevel) ) {
    if (!(dqfLevel %in% c(0, 1, 2, 3))) {
      stop(paste0("dqfLevel must be NULL, 0, 1, 2, or 3"))
    }
  }
  
  # ----- Filter Data ----------------------------------------------------------
  
  # create tibble
  tbl <- goesaodc_createTibble(nc)
  
  if (!is.null(bbox)) {
    lonLo <- bbox[1,1]
    lonHi <- bbox[1,2]
    latLo <- bbox[2,1]
    latHi <- bbox[2,2]
  }
  
  # filter tibble
  if (!is.null(lonLo)) {
    tbl <- dplyr::filter(tbl, .data$lon >= lonLo)
  }
  if (!is.null(lonHi)) {
    tbl <- dplyr::filter(tbl, .data$lon <= lonHi)
  }
  if (!is.null(latLo)) {
    tbl <- dplyr::filter(tbl, .data$lat >= latLo)
  }
  if (!is.null(latHi)) {
    tbl <- dplyr::filter(tbl, .data$lat <= latHi)
  }
  if (!is.null(dqfLevel)) {
    tbl <- dplyr::filter(tbl, .data$DQF <= dqfLevel)
  }
  
  if (nrow(tbl) == 0) {
    stop("No data for selected region")
  }
  
  # ----- Create SpatialPointsDataFrame ----------------------------------------
  
  spatialPoints <- sp::SpatialPointsDataFrame(
    coords = dplyr::select(tbl, c(.data$lon, .data$lat)),
    data = dplyr::select(tbl, -c(.data$lon, .data$lat))
  )
  
  return(spatialPoints)
  
}
