#' @export
#' 
#' @title Open a GOES AOD netCDF file
#' 
#' @description Opens a NetCDF file and returns the \code{nc} handle. By 
#' default, the directory specified with \code{setSatelliteDataDir()} is 
#' searched for the file.
#' 
#' @details
#' Errors generated by `nc_open()` are not handled and will pass through to the
#' console or calling function.
#' 
#' @param filename File name of GOES AOD file.
#' @param dataDir Data directory containing \code{filename}; Defaults to 
#' \code{getSatelliteDataDir()}.
#' 
#' @return nc handle
#' 
#' @seealso \code{\link{getSatelliteDataDir}}
#' 
#' @examples
#' \dontrun{
#' library(MazamaSatelliteUtils)
#' setSatelliteDataDir("~/Data/Satellite")
#' 
#' goesaodc_downloadAOD(
#'   satID = "G16", 
#'   datetime = "201924918", 
#'   timezone = "UTC", 
#'   isJulian = TRUE
#' )
#'   
#' netCDF <- "OR_ABI-L2-AODC-M6_G16_s20192491826095_e20192491828468_c20192491835127.nc"
#' 
#' nc <- goesaodc_openFile(netCDF)
#' }

goesaodc_openFile <- function(
  filename = NULL,
  dataDir = getSatelliteDataDir()
) {
  
  # ----- Validate parameters --------------------------------------------------
  
  MazamaCoreUtils::stopIfNull(filename)
  
  # ----- Open nc handle -------------------------------------------------------
  
  # Check if internal package file is being used
  if ( stringr::str_detect(filename, "extdata") ) { 
    fullPath <- filename
  } else {
    fullPath <- file.path(dataDir, filename)
  }

  if ( !file.exists(fullPath) )
    stop(paste0("Cannot find ", fullPath))
  
  # Let nc_open error messages bubble up 
  nc <- ncdf4::nc_open(fullPath)
  
  # ----- Return ---------------------------------------------------------------
  
  return(nc)
  
}
