#' @export
#' 
#' @title Open a GOES AOD netCDF file
#' 
#' @param filename file name of GOES AOD file
#' @param dataDir data directory containing \code{filename}
#' 
#' @description Uses \code{ncdf4::nc_open()} to open a NetCDF file and returns
#' the \code{nc} handle. By default, the directory specified with 
#' \code{setSatelliteDataDir()} is searched for the file.
#' 
#' Errors generated by `nc_open()` are unhandled and will pass through to the
#' console or calling function.
#' 
#' @return nc handle.
#' 
#' @seealso \code{\link{getSatelliteDataDir}}
#' 
#' @examples
#' \donttest{
#' setSatelliteDataDir("~/Data/Satellite")
#' nc <- goesaodc_openFile("OR_ABI-L2-AODC-M6_G16_s20191291201274_e20191291204047_c20191291210009.nc")
#' }

goesaodc_openFile <- function(
  filename = NULL,
  dataDir = getSatelliteDataDir()
) {
  
  if ( is.null(filename) )
    stop("Required parameter 'filename' is missing.")
  
  fullPath <- file.path(dataDir, filename)
  
  # Let nc_open error messages bubble up 
  nc <- ncdf4::nc_open(fullPath)
  
  return(nc)
  
}
