#' @export
#' 
#' @title Create a RasterStack for a specified hour
#' 
#' @param satId ID number of the source GOES satellite
#' @param startdate startdate, specified to the hour, in any Y-m-d H format or
#' \code{POSIXct}
#' @param var variable ("AOD, "DQF" or "ID"). Set to AOD by default.
#' @param res resolution of raster in degrees. Set to 0.1 by default.
#' @param bbox bounding box generated by \code{sp::bbox}, \code{raster::extent} 
#' or a vector of floats in c(lonLo, lonHi, latLo, latHi) order.
#' @param dqfLevel data quality flag level, numeric (0, 1, 2, or 3)
#' 
#' @description Create a \code{RasterStack} from GOES AOD data files for the 
#' date and hour specified by \code{startdate}. Each \code{RasterLayer} contains
#' data from one Advanced Baseline Imager (ABI) scan during the specified time 
#' period.
#' 
#' If data for the specified time period is not found in the directory specified 
#' by \code{setSatelliteDataDir()}, it will be downloaded in order to create the
#' \code{RasterStack}.
#' 
#' The Z axis of the \code{RasterStack} is a character vector where each element
#' is the time stamp of the scan and has the format YYYYMMDDHHMMSS. This can be 
#' accessed using the \code{raster::getZ()} function. Names of the 
#' \code{RasterStack} are also time stamps of the scan, of the format XHH.MM.SS.
#' 
#' Data quality level `dqfLevel` can take a value of:
#' 
#' 0: High quality retrieval flag
#' 1: Medium quality retrieval flag
#' 2: Low quality retrieval flag
#' 3: No retrieval quality flag
#' 
#' @return RasterStack
#' 
#' @examples
#' \donttest{
#' ### EXTENTS BASED ON PASSED IN FLOATS
#' library(MazamaSatelliteUtils)
#' setSatelliteDataDir("~/Data/Satellite")
#' 
#' bbox_us <- c(-124.848974, -66.885444, 24.396308, 49.384358) # US LOWER 48
#' 
#' rstrStack <- goesaodc_createHourlyRasterStack(
#' satId = "G16", 
#' startdate = "2019-09-06 16", 
#' bbox = bbox_us,
#' dqfLevel = 2,
#' res = 0.2)
#' 
#' rasterVis::levelplot(rstrStack)
#' 
#' #### EXTENTS BASED ON sp::bbox OF OREGON
#' library(MazamaSpatialUtils)
#' 
#' setSpatialDataDir("~/Data/Spatial")
#' loadSpatialData("USCensusStates")
#' 
#' oregon <- subset(USCensusStates, stateCode == "OR")
#' bbox_oregon <- sp::bbox(oregon)
#' 
#' rstrStack <- goesaodc_createHourlyRasterStack(
#' satId = "G17", 
#' startdate = "2019-09-06 16", 
#' bbox = bbox_oregon,
#' dqfLevel = 2)
#' 
#' rasterVis::levelplot(rstrStack)
#' }

goesaodc_createHourlyRasterStack <- function(
  satId = NULL,
  startdate = NULL,
  var = "AOD",
  res = 0.1,
  bbox = NULL,
  dqfLevel = NULL
) {
  
  # ----- Validate Input -------------------------------------------------------
  
  satId <- toupper(satId)
  if (!(satId %in% c("G16", "G17"))) {
    stop("Must specify GOES satellite ID (G16 or G17)")
  }
  
  if (!is.null(startdate)) {
    suppressWarnings({
      dt <- MazamaCoreUtils::parseDatetime(startdate, timezone = "UTC")
      #dt <- lubridate::parse_date_time(startdate, "Ymd HMS", tz = "UTC")
    })
    if (is.na(dt)) {
      stop("Parameter 'startdate' must be specified to the hour")
    }
  } else {
    stop("Parameter 'startdate' is required")
  }
  
  # ----- Download GOES AOD Files ----------------------------------------------
  
  # make sure that files are downloaded
  goesaodc_downloadAOD(satId, dt)
  
  # ----- Create List of RasterLayers ------------------------------------------
  
  # create list of AOD raster layers for specified hour and region
  rasterList <- 
    goesaodc_listFiles(satId, dt) %>%                   # create list of filenames for specified hour
    purrr::map(goesaodc_openFile) %>%                   # open each file in the list
    purrr::map(goesaodc_createRaster, res = res,        # rasterize each open file specified params
               bbox = bbox,                             
               dqfLevel = dqfLevel) %>%  
    purrr::map(function(rst) rst[[var]])                # select RasterLayer of specified variable
  
  # ----- Create RasterStack ---------------------------------------------------
  
  # Extents won't match exactly and raster::stack() needs them to, so
  # find the largest extent necessary to encompass all RasterLayers in the
  # list, and apply that new extent to each of the RasterLayers.
  lonLo <- min(purrr::map_dbl(rasterList, function(rst) raster::extent(rst)@xmin))
  lonHi <- max(purrr::map_dbl(rasterList, function(rst) raster::extent(rst)@xmax))
  latLo <- min(purrr::map_dbl(rasterList, function(rst) raster::extent(rst)@ymin))
  latHi <- max(purrr::map_dbl(rasterList, function(rst) raster::extent(rst)@ymax))
  
  ext <- raster::extent(c(lonLo, lonHi, latLo, latHi))
  
  rasterList <- purrr::map(rasterList, function(rst) raster::setExtent(rst, ext))
  
  # now create the stack
  rasterStack <- raster::stack(rasterList)
  
  # assign times to the Z axis
  times <-
    goesaodc_listFiles(satId, dt) %>%
    purrr::map_chr(goesaodc_getStartString) %>%
    purrr::map(lubridate::parse_date_time, orders = ("YjHMS"))
  
  Z <- purrr::map(times, strftime, format = "%Y%m%d%H%M%S", tz = "UTC")
  
  rasterStack <- raster::setZ(rasterStack, Z)
  # NOTE: Why does this prepend "X" to the names?
  names <- purrr::map(times, strftime, format = "%H:%M:%S", tz = "UTC")
  names(rasterStack) <- names
  
  return(rasterStack)
}
