#' @export
#' @importFrom rlang .data
#' 
#' @title Create a SpatialPointsDataFrame of GOES data
#' 
#' @param nc ncdf4 handle
#' @param bbox bounding box generated by \code{sp::bbox}. Overrides lonLo, lonHi
#' latLo, latHi if provided
#' @param lonLo lower longitude extent
#' @param lonHi upper longitude extent
#' @param latLo lower latitude extent
#' @param latHi upper latitude extent
#' @param dqfLevel data quality flag level
#' 
#' @description Create a SpatialPointsDataFrame of GOES data including data
#' within the specified extent and data quality flag level. Data quality level
#' can take a value of:
#' 
#' 0: High quality retrieval flag
#' 1: Medium quality retrieval flag
#' 2: Low quality retrieval flag
#' 3: No retrieval quality flag
#' 
#' 
#' @return SpatialPointsDataFrame

goesaodc_createSpatialPoints <- function(
  nc,
  bbox = NULL,
  lonLo = NULL,
  lonHi = NULL,
  latLo = NULL,
  latHi = NULL,
  dqfLevel = NULL
) {
  
  # ----- Validate Parameters --------------------------------------------------
  
  if ( !is.null(dqfLevel) ) {
    if (!(dqfLevel %in% c(0, 1, 2, 3))) {
      stop(paste0("dqfLevel must be NULL, 0, 1, 2, or 3"))
    }
  }
  
  # ----- Filter Data ----------------------------------------------------------
  
  # create tibble
  tbl <- goesaodc_createTibble(nc)
  
  if (!is.null(bbox)) {
    lonLo <- bbox[1,1]
    lonHi <- bbox[1,2]
    latLo <- bbox[2,1]
    latHi <- bbox[2,2]
  }
  
  # filter tibble
  if (!is.null(lonLo)) {
    tbl <- dplyr::filter(tbl, .data$lon >= lonLo)
  }
  if (!is.null(lonHi)) {
    tbl <- dplyr::filter(tbl, .data$lon <= lonHi)
  }
  if (!is.null(latLo)) {
    tbl <- dplyr::filter(tbl, .data$lat >= latLo)
  }
  if (!is.null(latHi)) {
    tbl <- dplyr::filter(tbl, .data$lat <= latHi)
  }
  if (!is.null(dqfLevel)) {
    tbl <- dplyr::filter(tbl, .data$DQF <= dqfLevel)
  }
  
  if (nrow(tbl) == 0) {
    stop("No data for selected region")
  }
  
  # ----- Create SpatialPointsDataFrame ----------------------------------------
  
  spatialPoints <- sp::SpatialPointsDataFrame(
    coords = dplyr::select(tbl, c(.data$lon, .data$lat)),
    data = dplyr::select(tbl, -c(.data$lon, .data$lat))
  )
  
  return(spatialPoints)
}

# ===== Debugging ==============================================================

if (FALSE) {
  projectDir <- "~/Code/Mazama/MazamaSatelliteUtils"
  
  # open file
  filePath <- paste0(projectDir, "/local_data/OR_ABI-L2-AODC-M3_G16_s20190781512186_e20190781514559_c20190781516459.nc")
  nc <- ncdf4::nc_open(filePath)
  
  # get bbox for Texas
  loadSpatialData("USCensusStates")
  tx <- subset(USCensusStates, stateCode == "TX")
  bb_tx <- sp::bbox(tx)
  
  # create SpatialPointsDataFrame
  spatialPoints <- goesaodc_createSpatialPoints(nc, bb_tx)
  
  # plot
  goesaodc_plotSpatialPoints(spatialPoints, n=1e4)
  plot(tx, add=T)
}
