#' @export
#' 
#' @title Create a RasterStack for a specified hour
#' 
#' @param startdate startdate, specified to the hour, in any Y-m-d H format or
#' \code{POSIXct}
#' @param satId ID number of the source GOES satellite
#' @param var variable ("AOD, "DQF" or "ID")
#' @param res resolution of raster in degrees
#' @param fun function to use when rasterizing. Not currently supported, defaults
#' to mean.
#' @param bbox bounding box generated by \code{sp::bbox}. Overrides lonLo, lonHi
#' latLo, latHi if provided
#' @param lonLo lower longitude extent
#' @param lonHi upper longitude extent
#' @param latLo lower latitude extent
#' @param latHi upper latitude extent
#' @param dqfLevel data quality flag level, numeric (0, 1, 2, or 3)
#' 
#' @description Create a \code{RasterStack} from GOES AOD data files for the 
#' date and hour specified by \code{startdate}. Each \code{RasterLayer} contains
#' data from one Advanced Baseline Imager (ABI) scan during the specified time 
#' period.
#' 
#' If data for the specified time period is not found in the directory specified 
#' by \code{setSatelliteDataDir()}, it will be downloaded in order to create the
#' \code{RasterStack}.
#' 
#' The Z axis of the \code{RasterStack} is a character vector where each element
#' is the time stamp of the scan and has the format YYYYMMDDHHMMSS. This can be 
#' accessed using the \code{raster::getZ()} function. Names of the 
#' \code{RasterStack} are also time stamps of the scan, of the format XHH.MM.SS.
#' 
#' Data quality level `dqfLevel` can take a value of:
#' 
#' 0: High quality retrieval flag
#' 1: Medium quality retrieval flag
#' 2: Low quality retrieval flag
#' 3: No retrieval quality flag
#' 
#' @return RasterStack
#' 
#' @examples
#' \donttest{
#' setSatelliteDataDir("~/Data/Satellite")
#' date <- lubridate::ymd_h("2019-05-16 16", tz = "UTC")
#' rstrStack <- goesaodc_createHourlyRasterStack(startdate = date, satId = 16, 
#'                                               res = 0.2)
#' rasterVis::levelplot(rstrStack)
#' }

goesaodc_createHourlyRasterStack <- function(
  startdate = NULL,
  satId = NULL,
  var = "AOD",
  res = 0.1,
  fun = mean,
  bbox = NULL,
  lonLo = NULL,
  lonHi = NULL,
  latLo = NULL,
  latHi = NULL,
  dqfLevel = NULL
) {
  
  # ----- Validate Input -------------------------------------------------------
  
  if (!is.null(startdate)) {
    suppressWarnings({
      #dt <- lubridate::parse_date_time(startdate, "YmdH", tz = "UTC")
      dt <- lubridate::parse_date_time(startdate, "Ymd HMS", tz = "UTC")
    })
    if (is.na(dt)) {
      stop("Parameter 'startdate' must be specified to the hour")
    }
  } else {
    stop("Parameter 'startdate' is required")
  }
  
  if (is.null(satId)) {
    stop("Must specify GOES satellite ID (16 or 17)")
  }
  
  # ----- Download GOES AOD Files ----------------------------------------------
  
  # make sure that files are downloaded
  goesaodc_downloadAOD(dt, satId = satId)
  
  # ----- Create List of RasterLayers ------------------------------------------
  
  # create list of AOD raster layers for specified hour and region
  rasterList <- 
    goesaodc_listFiles(dt, satId = satId) %>%           # create list of filenames for specified hour
    purrr::map(goesaodc_openFile) %>%                   # open each file in the list
    purrr::map(goesaodc_createRaster, res = res,        # rasterize each open file specified params
               # fun = fun,                             # NOTE: passing fun here does not work. Results in
               bbox = bbox,                             # NOTE: the following error: 
               lonLo = lonLo, lonHi = lonHi,            # NOTE: Error in fun(1) : could not find function "fun"
               latLo = latLo, latHi = latHi, 
               dqfLevel = dqfLevel) %>%  
    purrr::map(function(rst) rst[[var]])                # select RasterLayer of specified variable
  
  # ----- Create RasterStack ---------------------------------------------------
  
  # Extents won't match exactly and raster::stack() needs them to, so
  # find the largest extent necessary to encompass all RasterLayers in the
  # list, and apply that new extent to each of the RasterLayers.
  lonLo <- min(purrr::map_dbl(rasterList, function(rst) raster::extent(rst)@xmin))
  lonHi <- max(purrr::map_dbl(rasterList, function(rst) raster::extent(rst)@xmax))
  latLo <- min(purrr::map_dbl(rasterList, function(rst) raster::extent(rst)@ymin))
  latHi <- max(purrr::map_dbl(rasterList, function(rst) raster::extent(rst)@ymax))
  
  ext <- raster::extent(c(lonLo, lonHi, latLo, latHi))
  
  rasterList <- purrr::map(rasterList, function(rst) raster::setExtent(rst, ext))
  
  # now create the stack
  rasterStack <- raster::stack(rasterList)
  
  # assign times to the Z axis
  times <-
    goesaodc_listFiles(dt, satId = satId) %>%
    purrr::map_chr(goesaodc_getStartString) %>%
    purrr::map(lubridate::parse_date_time, orders = ("YjHMS"))
  
  Z <- purrr::map(times, strftime, format = "%Y%m%d%H%M%S", tz = "UTC")
  
  rasterStack <- raster::setZ(rasterStack, Z)
  # NOTE: Why does this prepend "X" to the names?
  names <- purrr::map(times, strftime, format = "%H:%M:%S", tz = "UTC")
  names(rasterStack) <- names
  
  return(rasterStack)
}
