#' @export
#' @importFrom rlang .data
#'
#' @title Create a SpatialPointsDataFrame of GOES data
#'
#' @param nc ncdf4 handle
#' @param bbox bounding box generated by \code{sp::bbox}. Overrides lonLo, lonHi
#' latLo, latHi if provided
#' @param lonLo lower longitude extent
#' @param lonHi upper longitude extent
#' @param latLo lower latitude extent
#' @param latHi upper latitude extent
#' @param dqfLevel data quality flag level
#'
#' @description Create a SpatialPointsDataFrame of GOES data including data
#' within the specified extent and data quality flag level. Data quality level
#' can take a value of:
#'
#' \itemize{
#' \item{0}{ -- High quality retrieval flag}
#' \item{1}{ -- Medium quality retrieval flag}
#' \item{2}{ -- Low quality retrieval flag}
#' \item{3}{ -- No retrieval quality flag}
#' }
#'
#' @return SpatialPointsDataFrame
#'
#' @examples
#' \donttest{
#' library(MazamaSatelliteUtils)
#' setSatelliteDataDir("~/Data/Satellite")
#' netCDF <- system.file("extdata",
#'                       "OR_ABI-L2-AODC-M6_G16_s20192491826095_e20192491828468_c20192491835127.nc",
#'                       package = "MazamaSatelliteUtils")
#' nc <- ncdf4::nc_open(netCDF)
#' sp <- goesaodc_createSpatialPoints(nc, dqfLevel = 1)
#' maps::map("state")
#' goesaodc_plotSpatialPoints(sp, cex = 0.3, add = TRUE)
#' }

goesaodc_createSpatialPoints <- function(
  nc,
  bbox = NULL,
  lonLo = NULL,
  lonHi = NULL,
  latLo = NULL,
  latHi = NULL,
  dqfLevel = NULL
) {
  
  # ----- Validate parameters --------------------------------------------------
  
  if ( !is.null(dqfLevel) ) {
    if (!(dqfLevel %in% c(0, 1, 2, 3))) {
      stop(paste0("dqfLevel must be NULL, 0, 1, 2, or 3"))
    }
  }
  
  # ----- Filter data ----------------------------------------------------------
  
  # create tibble
  tbl <- goesaodc_createTibble(nc)
  
  if (!is.null(bbox)) {
    boundaries <- bboxToVector(bbox)
    lonLo <- boundaries[1]
    lonHi <- boundaries[2]
    latLo <- boundaries[3]
    latHi <- boundaries[4]
  }
  
  # filter tibble
  if (!is.null(lonLo)) {
    tbl <- dplyr::filter(tbl, .data$lon >= lonLo)
  }
  if (!is.null(lonHi)) {
    tbl <- dplyr::filter(tbl, .data$lon <= lonHi)
  }
  if (!is.null(latLo)) {
    tbl <- dplyr::filter(tbl, .data$lat >= latLo)
  }
  if (!is.null(latHi)) {
    tbl <- dplyr::filter(tbl, .data$lat <= latHi)
  }
  if (!is.null(dqfLevel)) {
    tbl <- dplyr::filter(tbl, .data$DQF <= dqfLevel)
  }
  
  if (nrow(tbl) == 0) {
    stop("No data for selected region")
  }
  
  # ----- Create SpatialPointsDataFrame ----------------------------------------
  
  spatialPoints <- sp::SpatialPointsDataFrame(
    coords = dplyr::select(tbl, c(.data$lon, .data$lat)),
    data = dplyr::select(tbl, -c(.data$lon, .data$lat))
  )
  
  return(spatialPoints)
  
}
