#' @export
#' 
#' @title Create a RasterBrick Average for a specified hour
#' 
#' @param startdate startdate, specified to the hour, in any Y-m-d H format or
#' \code{POSIXct}
#' @param res resolution of raster in degrees
#' @param bbox bounding box generated by \code{sp::bbox}.
#' @param dqfLevel data quality flag level, numeric (0, 1, 2, or 3)
#' 
#' @description Create 
#' 
#' Data quality level `dqfLevel` can take a value of:
#' 
#' 0: High quality retrieval flag
#' 1: Medium quality retrieval flag
#' 2: Low quality retrieval flag
#' 3: No retrieval quality flag
#' 
#' @return RasterBrick
#' 
#' @examples
#' \donttest{
#' }

goesaodc_createHourlyAverageRaster <- function(
  startdate = NULL,
  state = NULL, 
  res = 0.1,
  dqfLevel = NULL,
  na.rm = TRUE
) {
  
  state_bbox <- sp::bbox(state)
  
  rstrStack <- goesaodc_createHourlyRasterStack(startdate = startdate, 
                                                bbox = state_bbox,
                                                res = res, 
                                                dqfLevel = dqfLevel)
  
  stackAvg <- mean(rstrStack, na.rm = na.rm)
  
  return(stackAvg)
}

# Debug
if (FALSE) {
  
  # Library setup
  library(MazamaSatelliteUtils)
  library(MazamaSpatialUtils)
  setSatelliteDataDir("~/Data/Satellite")
  setSpatialDataDir("~/Data/Spatial")
  loadSpatialData("USCensusStates")
  
  # Define params
  oregon <- subset(USCensusStates, stateCode == "OR")
  date <- lubridate::ymd_h("2019-07-31 16", tz = "UTC")
  
  avg <- goesaodc_createHourlyAverageRaster(date, oregon)
  
  # Define AOD palette
  pal_aod <- colorRampPalette(c("lightgoldenrod1", "red3"))
  breaks_aod <- seq(-2.5, 2.5, by = 0.05)
  
  # Plot average AOD raster and state border
  plot(avg, col = pal_aod(100), breaks = breaks_aod, main = "Average AOD")
  plot(oregon, add = TRUE)
} 

